[package]
name = "sf_planner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ratatui = { version = "0.28.0", features = ["all-widgets", "crossterm"] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
thiserror = "1.0.63"
